apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: kaniko
spec:
  containers:
  - name: nodego
    image: tyagivasu/ubuntu-v1:16.04
    command: ['cat']
    tty: true
    volumeMounts:
      - name: sharedvolume
        mountPath: /var/sharedvolume
    resources:
      requests:
        cpu: "50m"
        memory: "124Mi"
      limits:
        cpu: "2000m"
        memory: "2048Mi"

  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    args: ["--dockerfile=dockerfile",
           "--context=/kaniko/sharedvolume"]
    volumeMounts:
      - name: sharedvolume
        mountPath: /kaniko/sharedvolume
    resources:
      requests:
        cpu: "50m"
        memory: "124Mi"
      limits:
        cpu: "2000m"
         memory: "2048Mi"

  #restartPolicy: OnFailure
  volumes: 
    - name: sharedvolume
      emptyDir: {}