apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: nodego
    image: tyagivasu/ubuntu-v1:16.04
    command: ['cat']
    tty: true
    resources:
      requests:
        cpu: "50m"
        memory: "124Mi"
      limits:
        cpu: "2000m"
        memory: "2048Mi"

  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug-539ddefcae3fd6b411a95982a830d987f4214251
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /root
    resources:
      requests:
        cpu: "50m"
        memory: "124Mi"
      limits:
        cpu: "2000m"
        memory: "2048Mi"

  #restartPolicy: OnFailure
  volumes: 
    - name: jenkins-docker-cfg
      projected:
        sources:
        - secret:
            name: vikrant-docker
            items:
              - key: .dockerconfigjson
                path: .docker/config.json