apiVersion: v1
kind: Pod
spec:
  containers:
  - name: nodego
    image: tyagivasu/ubuntu-v1:16.04
    command: ['cat']
    tty: true
    volumeMounts:
    - mountPath: '/opt/app/shared'
      name: sharedvolume
  volumes: 
  - name: sharedvolume
    emptyDir: {}