apiVersion: v1
kind: Pod
spec:
  containers:
  - name: nodego
    image: tyagivasu/ubuntu-v1:16.04
    command: ['cat']
    tty: true
    volumeMounts:
      - name: sharedvolume
        mountPath: '/var/sharedvolume'

  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    volumeMounts:
      - name: sharedvolume
        mountPath: '/kaniko/sharedvolume'


  #restartPolicy: OnFailure
  volumes: 
  - name: sharedvolume
    emptyDir: {}